services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app_container
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - C:\Users\codys\Downloads:/data
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    command: sh -c "python main.py /data $APP_ARGS"

volumes:
  mongodb_data:
